# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  frontend:
    build:
      target: development
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    tty: true
    stdin_open: true
    
  backend:
    build:
      target: development
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

volumes:
  frontend_node_modules:
  backend_node_modules: