# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  database:
    build:
      context: ./database
    ports:
      - 5432:5432
    env_file:
      - database/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: