# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 5173:5173
    env_file:
      - frontend/.env
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - sachat-network
    depends_on:
      - backend
    command: sh -c "npm run dev -- --host 0.0.0.0"
    tty: true
    stdin_open: true
    
  backend:
    build:
      context: ./backend
    ports:
      - 3000:3000
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - sachat-network
    depends_on:
      - database
    command: sh -c "npx prisma migrate dev && npm run dev"

  database:
    build:
      context: ./database
    ports:
      - 5432:5432
    env_file:
      - database/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sachat-network

networks:
  sachat-network:
    driver: bridge

volumes:
  frontend_node_modules:
  backend_node_modules:
  postgres-data: